### ISSUE TITLE
✨ [24.10.09] 프로젝트 환경설정

### ISSUE THREAD

**Issue by s-ja** [Mt-NextJs/linkle#1]
## 작업 사항

라이브러리 설치 및 테스트, eslint 및 prettier 등의 포매터 등 본격적인 작업 시작 전 환경 설정 진행

## Todo

- [x] #2
- [x] #3
- [x] #4
- [x] #5
- [x] wiki 및 협업 관련 문서화
- [x] PR 을 위한 코드리뷰 시스템 등 협업 관련 설정
### 10.14 기준 추가 작업
- [x] 전달 api 관련 파일들 gitignore에 추가
- [x] 이슈 및 PR 분류를 위한 라벨 및 마일스톤 추가

## 기타

- Todo 각 항목은 하위  새로운 이슈로 관리 예정입니다.
- 라이브러리 및 도구 등은 필요에 따라 조정 및 추가 가능하며, 이 과정에서의 이슈 관리는 하위 이슈를 통해 관리할 예정입니다.
