### ISSUE TITLE
✨ [24.10.22] 이벤트 블록 퍼블리싱 및 기능 수정

### ISSUE THREAD

**Issue by wynter24** [Mt-NextJs/linkle#109]
## 작업 사항

기존 작업하던 이벤트 페이지 퍼블리싱, 일부 기능 수정 및 구현

## Todo

- [ ] 이벤트 블록 퍼블리싱
    - [x] 공통 컴폰넌트 적용 
    - [ ] 이벤트 일정 달력
- [ ] 기능 구현 
    - [x] 이벤트 명과 이벤트 설명이 정해진 글자 수를 초과할 경우, `...`으로 처리
    - [ ] 아래 화살표 추가하여 더보기 기능 추가
    - [ ] 남은 시간 계산 로직 수정
- [x] API 연결
