### ISSUE TITLE
✨ [24.10.10] 관리자 편집 페이지 퍼블리싱

### ISSUE THREAD

**Issue by Defor721** [Mt-NextJs/linkle#14]
## 작업 사항
관리자 편집 페이지 UI 구조 설계 및 일부 기능 구현

## Todo
- [ ] #26
- [ ] 드래그 앤 드롭 기능 구현
- [x] 기본 UI 구조 설계
- [x] UI 일부 구현
