### ISSUE TITLE
✨ [24.10.28] 더보기 버튼 구현

### ISSUE THREAD

**Issue by wynter24** [Mt-NextJs/linkle#164]
## 작업 사항

텍스트가 잘리는 경우에 사용자가 화살표 아이콘을 눌러서 카드의 내용을 확장합니다.

## Todo

- [x] 상태 정의 및 DOM 참조
    - 상태 (`isExpanded`, `isDescriptionOverflowing`, `isTitleOverflowing`): 확장 여부 및 설명과 제목의 길이 넘침 여부를 관리합니다.
    - 참조 (descriptionRef, titleRef): 실제 DOM 요소를 참조하여 길이 넘침 여부를 확인합니다.
- [x] useEffect로 텍스트 넘침 여부 확인
    - 텍스트 넘침 여부를 확인: 컴포넌트가 처음 렌더링될 때와 description 또는 title이 변경될 때마다 실행됩니다.
    - scrollWidth와 clientWidth를 비교하여 텍스트가 잘리는지 판단합니다.
    - 만약 카드가 확장된 상태에서 텍스트가 넘치지 않는 경우, 자동으로 isExpanded 상태를 false로 설정합니다 
- [x] 카드 확장/축소 토글 함수(`handleExpandToggle`)
    - 사용자가 화살표 아이콘을 클릭할 때 호출: 제목 또는 설명이 잘리는 경우에만 카드를 확장/축소할 수 있습니다.

#### 코드
```
// 상태
const [isExpanded, setIsExpanded] = useState<boolean>(false); // 카드 확장 여부
const [isDescriptionOverflowing, setIsDescriptionOverflowing] = useState<boolean>(false); // 설명 텍스트 넘침 여부
const [isTitleOverflowing, setIsTitleOverflowing] = useState<boolean>(false); // 타이틀 텍스트 넘침 여부

// 참조
const descriptionRef = useRef<HTMLParagraphElement>(null);
const titleRef = useRef<HTMLParagraphElement>(null);

// 넘침 여부 확인
useEffect(() => {
  if (descriptionRef.current) {
    setIsDescriptionOverflowing(
      descriptionRef.current.scrollWidth > descriptionRef.current.clientWidth,
    );
  }
  if (titleRef.current) {
    setIsTitleOverflowing(
      titleRef.current.scrollWidth > titleRef.current.clientWidth,
    );
  }
  // 카드가 확장된 상태에서 텍스트가 넘치지 않는다면 확장 상태 해제
  if (isExpanded && (isDescriptionOverflowing || isTitleOverflowing)) {
    setIsExpanded(false);
  }
}, [description, title, isDescriptionOverflowing, isTitleOverflowing]);

// 카드 확장 및 축소
const handleExpandToggle = () => {
  if (isDescriptionOverflowing || isTitleOverflowing) {
    setIsExpanded(!isExpanded);
  }
};
```

- 상태에 따라 달라지는 스타일 설정은 `app\admin\(block)\event\components\event-preview.tsx`에서 확인해주세요.
