### ISSUE TITLE
✨ [24.10.30] 세션에서 쿠키로의 토큰 이용 방식 개선

### ISSUE THREAD

**Issue by s-ja** [Mt-NextJs/linkle#189]
## 작업 사항

- 비로그인 사용자에 대한 페이지 이동 기능을 담당하고 있는 미들웨어를 비롯, SSR을 활용하는 측면에서 세션보다 쿠키가 더 적절할 것으로 판단,
- 현재 세션에서 가져오고 있는 토큰을 쿠키로 일괄 변경
- 보안 관련 예상 문제에 대한 조치와 관련 도구 설치를 포함

## Todo

- [ ] 토큰 관리 및 코드 가독성을 위한 라이브러리 [js-cookie](https://www.npmjs.com/package/js-cookie) 설치 및 테스트
- [ ] 로그인 페이지의 세션 토큰 저장 코드 제거
- [ ] 각 페이지 혹은 api 호출 유틸에 세션 기반 토큰 사용 코드 쿠키 기반으로 교체 및 수정
- [ ] 각 페이지 작동 테스트
- [ ] 세션에서 쿠키 기반으로의 이동으로 인한 보안 관련 조치 진행

## 기타

- 보안 관련 조치 진행 중, 쿠키 유효 시간 설정으로 인한 사용성 변경 예상
- 현재 백엔드에서의 토큰 무효화 시간에 대한 정보가 없는 것으로 기억, 관련 정보 확인 필요
- 설정한 쿠키 유효 시간 만료 후, 알림과 함께 로그아웃, 인트로 혹은 로그인 화면으로 이동 시키는 로직 필요.
  - SSR 기반에서 쿠키 만료에 따른 클라이언트 변경 감지 + 클라이언트 측 알림 띄우기 관련 조사가 필요할 것으로 예상
  - #83
