### ISSUE TITLE
✨ [24.10.30] block 페이지 api utils 적용, block layout 에서 뒤로가기 link 적용

### ISSUE THREAD

**Issue by lumpenop** [Mt-NextJs/linkle#194]
## Todo

- [ ] block 페이지 에서 utils 에 수정된 api 호출 로직을 사용하도록 수정
- [ ] get token util 작성 (api 호출 로직에서 token 가져오는 로직 분리하여 client side 에서 적용)
- [ ] block layout 에서 기존 button 식으로 사용되던 뒤로가기 link 에 href 를 사용할 수 있도록 수정
