### ISSUE TITLE
✨ [24.11.15] 캘린더, 구분선, 이벤트, 이미지 블록 SEO 및 웹 접근성 최적화 작업 

### ISSUE THREAD

**Issue by cchaeyoung** [Mt-NextJs/linkle#248]
## 작업 사항

캘린더, 구분선, 이벤트, 이미지 블록 SEO 및 웹 접근성 최적화 작업 진행

## Todo

SEO 작업
- [x] 메타 태그 최적화
  - [x] 메타 태그 설정
  - [x] 메타 설명 작성
  - [x] Open Graph (OG) 태그 설정
- [x] 이미지 최적화
  - [x]  alt 텍스트 추가 및 점검
- [x] 파비콘 설정

웹 접근성 개선 작업
- [x] alt 텍스트 추가 및 점검
  - [x] 모든 이미지에 alt 텍스트 추가
   - [x] 이미지의 역할에 따라 empty alt (alt="") 설정
- [x] 시맨틱 HTML 태그 사용
  - [x] header, main, article, section 등 시맨틱 태그 사용
- [x]  ARIA 속성 추가
  - [x]  `aria-label` 속성 추가
  - [x]  `aria-labelledby` 속성 추가
  - [x]  `role` 속성 추가
- [x]  키보드 탐색 가능성 개선
  - [x]  탭 순서 점검 및 수정
