### ISSUE TITLE
✨ [24.11.16] 전체 코드 개선 및 UI/UX 향상 작업

### ISSUE THREAD

**Issue by wynter24** [Mt-NextJs/linkle#250]
## 작업 사항

UI/UX개선, 코드 리팩토링, 기능적 오류 수정, Tailwind 속성 적용, 웹 접근성 개선

## Todo

- link-form
    - [ ] (기능)심플 선택 시 입력된 이미지 URL 사라지는 에러 해결
    - [ ]  URL 형식 경고 메시지 수정
    - [ ]  (tailwind) `after:content-['*']` 속성 추가
- style-preview
    - [ ] 각 스타일 타입 컴포넌트로 분리
    - [ ] selectedStyle 타입 정해진 문자열 리터럴 타입으로 제한("썸네일" | "심플" | "카드" | "배경”)
    - [ ] selectedStyle에 따라 렌더링하는 부분에서 중복된 코드 변수로 분리
    - [ ] 카드 타입 animation 수정
- 공통 (웹 접근성 최적화)
    - [ ] Aria Label 추가
