### ISSUE TITLE
✨ [24.11.16] 이벤트 블록 전체 코드 및 UI/UX 개선

### ISSUE THREAD

**Issue by wynter24** [Mt-NextJs/linkle#251]
## 작업 사항

코드 리팩토링 및 성능 최적화: 상태 관리 개선, 불필요한 리렌더링 방지, 가독성 및 유지보수성 향상

## Todo

- event-from
    - [ ] id 속성에서 "evnet" 오타 수정
    - [ ] form 제출 후 데이터 초기화
    - [ ] combineDateAndTime 함수를 유틸리티 함수로 분리하여 재사용성 높이기
- event-date-picker
    - [ ] DateInput과 TimeInput 컴포넌트 분리
    - [ ] 달력 패널 애니메이션 또는 전환 효과 개선
    - [ ] label 태그에 htmlFor,  DatePicker 태그에 id 속성 설정
    - [ ] 분리된 시작, 종료 달력 상태를 useReducer 를 사용하여 하나의 상태로 묶어 관리
- event-preview
    - [ ] useState 대신 useReducer 로 상태 관리
    - [ ] setInterval 대신 setTimeout 사용하여 비효율적인 리렌더링 방지
    - [ ] IoIosArrowDown 버튼에 aria-expanded 속성 추가

## 기타

변경사항 적용 과정에서 수정이 있을 수 있습니다.
