### ISSUE TITLE
✨ [24.10.13] 인터랙션이 없는 영역 서버 컴포넌트로 변환

### ISSUE THREAD

**Issue by lumpenop** [Mt-NextJs/linkle#28]
## Todo
- [ ] 인터랙션 없는 영역 서버 컴포넌트로 변환
- [ ] input form 을 server action 으로 변환
- [ ] 인터랙션이 필요한 영역 끼리만 Context 로 상태 공유

**Comment by lumpenop** [comment]
인터랙션이 없는 영역이 필요한 영역과 형제 컴포넌트라 레이아웃 영역에만 적용 가능할듯..
