### ISSUE TITLE
✨ [24.11.26] main -> profile/[userId] , intro -> main 페이지 이동 및 profile api 연동

### ISSUE THREAD

**Issue by lumpenop** [Mt-NextJs/linkle#282]
## Todo

- [ ] main -> profile/[userId]  
- [ ] intro -> main 페이지 이동 
- [ ] profile api 연동
