### ISSUE TITLE
✨ [24.11.27] admin 페이지 레아이웃(스타일) 조정

### ISSUE THREAD

**Issue by s-ja** [Mt-NextJs/linkle#299]
## 작업 사항

- 메인 페이지 스타일 완성

## Todo

- [ ] 다크모드를 위한 스타일 조정
- [ ] 반응형 디자인 구현
- [ ] 레이아웃 종합적인 조정
