### ISSUE TITLE
✨ [24.10.14] 랜딩페이지 구현

### ISSUE THREAD

**Issue by s-ja** [Mt-NextJs/linkle#32]
## Todo
- [x] 사용자 최초 접근 시, 로그인 여부 확인 기능 구현
- [x] 비 로그인 사용자에 대한 랜딩 페이지로의 라우팅
- [x] 랜딩 페이지 UI 디자인
- [x] 랜딩 페이지 퍼블리싱
- [x] 로그인 / 회원가입 페이지 링크

## 추가 작업 사항 (24.10.22 기준)
- [x] 이미 로그인 되어 있는 사용자에 대한 로그인 및 회원가입 페이지 접근 막기
  - 미들웨어와 서버 기능을 활용한 main 페이지로의 이동 : 빠르고 즉각적임, 보안적인 이점
  - useEffect를 이용한 클라이언트 측에서의 이동 : 세밀한 클라이언트 측 상태 관리 가능, 다양한 후처리(사용자 알림 등...) 가능

**Comment by s-ja** [comment]
랜딩페이지 관련 작업은 현재 이슈와 함께 우선 종료
이후 발생 문제에 대해서는 다른 이슈와 함께 다룰 예정
