### ISSUE TITLE
✨ [24.10.09] 라이브러리 및 도구 설정

### ISSUE THREAD

**Issue by s-ja** [Mt-NextJs/linkle#4]
## 작업 사항

논의 결과에 따른 사용 도구 및 라이브러리 도입, 설치와 관련된 이슈

## Todo
- [ ] **모노레포 설정**
  - [ ] 터보레포 세팅 및 워크스페이스 구조 정의
- [x] **스타일링 도구 설정**
  - [x] TailwindCSS 설치 및 초기 설정
- [ ] **테스팅 도구 설정**
  - [ ] Jest 및 React Testing Library 설치 및 세팅
- [ ] **상태 관리 도구 설정**
  - [ ] Zustand 설치 및 기본 상태 관리 구조 설정

## 기타

- 관련 조사 결과 및 진행 상황은 하위 이슈 혹은 해당 이슈에 기록할 예정입니다.
- 라이브러리 및 도구들은 필요와 상황에 따라 유동적으로 관리합니다.
- 상황에 따라 점진적이고 유동적으로 도구를 도입합니다.
- 도구 도입을 위한 구조 변경(예 : 터보레포)등의 추가 작업이 필요한 경우, 새로운 이슈를 생성, 관리합니다.
