### ISSUE TITLE
✨ [24.10.09] 프로젝트 빌딩 전 사전 배포

### ISSUE THREAD

**Issue by s-ja** [Mt-NextJs/linkle#5]
## 작업 사항

라이브러리 설치 및 테스트, eslint 및 prettier 등의 포매터 등 본격적인 작업 시작 전 환경 설정 진행

## Todo

- [x] develop 브랜치
  - [x] 브랜치 생성
  - [x] 브랜치 보호 규칙 설정
- [ ] vercel
  - [x] 프로젝트 설정
  - [x] ~~저장소 및 브랜치 연결~~ 저장소 관련 멘토님 권한 확인 필요
  - [ ] 빌드 및 배포 테스트
  - [ ] 발생 에러 및 문제 해결

## 기타

- 배포 과정에서 저장소 권한 등 멘토님 요청 필요 예상

**Comment by s-ja** [comment]
이후 즉각적인 테스트를 위해 로컬 main 브랜치 -> 원격 main 브랜치 로 직접 작업 진행
작업 과정에서 깃헙 액션 전략 변경 진행 `ad-m/github-push-action` 및 git 명령어 `deploy.yaml` 파일 내부에서 직접 실행 방법 등
인증 및 권한 관련 문제로 보이는 문제들 해결 과정에서 파일 내부에 git configure 명령어 추가와 더불어 다수의 토큰 권한 점검과 재생성, 재등록 진행
원격 저장소 커밋 불일치 문제 해결을 위해 원격 저장소 삭제 + 동일한 이름으로 재생성 다수 진행
원격 저장소 push 성공 이후에 사용 라이브러리들의 node 버전 경고 해결을 위해 노드 버전 변경 등 진행

결과적으로 gitignore에서의 git 추적 제외 패턴 중 build 가 build.sh를 포함하여 build.sh 파일이 추적되지 않았던 것이 가장 큰 원인이었던 것으로 추측

배포 성공 이후 git 명령어 직접 실행에서 ad-m/github-push-action 액션을 활용한 방법 테스트 결과 작동하지 않았음
인증 방법의 차이인 것으로 추측, 다른 작업을 위해 우선 작동하는 git 명령어 직접 호출 방법으로 유지.
간결한 코드를 위해 이후 추가 조사 가능

이후 작업 과정에서 약식으로 작성한 26개의 pr 및 해제해뒀던 브랜치 보호 규칙의 점검 및 복구 진행
다른 작업자들의 작업물 병합 및 배포 과정에서의 문제 발생 시 다른 이슈로 추적 예정
