### ISSUE TITLE
✨ [24.10.16] 이벤트 블록

### ISSUE THREAD

**Issue by wynter24** [Mt-NextJs/linkle#69]
## Todo

- [ ] 퍼블리싱
    - [x] 레이아웃 설계 및 배치
    - [ ] UI 작업
- [ ] 컴포넌트 분리
- [ ] 기능
    - [x] 캘린더 라이브러리(react-datepicker)
    - [ ] 블록 미리보기 : 선택한 날짜, 남은 시간 계산
    - [ ] API 연결
  

## 기타

상세 디자인이 확정되면 일부 디자인이 변경될 수 있습니다.
