### ISSUE TITLE
✨ [24.10.10] 링크 블록

### ISSUE THREAD

**Issue by wynter24** [Mt-NextJs/linkle#8]
## 작업 사항

링크 블록 퍼블리싱 및 기능 구현

## Todo
- [x] 전체 레이아웃 구성
    - [x] 페이지 구조 설계
    - [x] 주요 섹션 배치
    - [x] 스타일 섹션의 블록 타입
- [ ] UI 작업
- [x] 컴포넌트로 분리
    - [x] link-form: 서버로 전송될 데이트
    - [x] style-preview: 상단의 스타일 타입 미리보기
    - [x] style-type: 스타일의 4개의 타입
    - [x] Info: 연결할 주소, 타이틀, 이미지
 - [x] 기능 구현
    - [x] 스타일 타입별 링크 블록 미리보기 변환
         - [x] ~~변환시 1-2초 지연~~ → tailwind transition 사용
    - [x] 이미지 미리보기
    - [x] 이미지 URL validation #41  
    - [x] #68 
    - [x] #75

## 기타

- 상세 디자인이 확정되면 일부 디자인이 변경될 수 있습니다
