### ISSUE TITLE
✨ [24.10.20] 이미지, 동영상 박스 css 변경, 각 url 유효성 검사

### ISSUE THREAD

**Issue by lumpenop** [Mt-NextJs/linkle#88]
## Todo

- [x] 이미지, 동영상 박스 주변 shadow
- [x] 이미지, 동영상 박스 크기 조절
- [x] 이미지, 동영상 url 유효성 검사
