### ISSUE TITLE
✨ [24.10.10] 이미지 블록

### ISSUE THREAD

**Issue by lumpenop** [Mt-NextJs/linkle#9]
## Todo
- [x] 이미지 최적화 조사
- [x] 이미지 최적화 및 외부 URL  이미지 허용 설정 (next config) 
- [x] 이미지 블록 컴포넌트 작성

## 이미지 최적화
- Next.js 에서 next/image 사용 시 gif, svg 를 제외한 이미지에 대해 자동으로 최적화가 진행됨
- svg 의 경우 보안 이슈로 인해 따로 설정을 해줘야 최적화 가능
- 추가 최적화가 필요한 경우 sharp 라이브러리 사용 권장

### svg 최적화

SVG 이미지 처리와 dangerouslyAllowSVG
SVG 이미지는 벡터 기반으로 확대나 축소가 자유롭지만, XSS 공격과 같은 보안 문제를 야기할 수 있습니다. 
dangerouslyAllowSVG는 SVG 파일을 최적화 과정에 포함시킬지 결정하는 설정입니다. 
이 설정을 활성화하면, Next.js는 SVG 이미지에 대한 최적화를 시도하지만, 이때 추가적인 보안 조치를 취하는 것이 좋습니다.
```
// next.config.js
module.exports = {
  images: {
    dangerouslyAllowSVG: true,
    contentDispositionType: 'attachment',
    contentSecurityPolicy: "default-src 'self'; script-src 'none'; sandbox;",
  },
}
```
 브라우저가 이미지를 다운로드하도록 contentDispositionType을 강제로 설정하고, 이미지에 포함된 스크립트 실행을 방지하기 위해 contentSecurityPolicy를 설정하는 것이 강력하게 권장됩니다.
