### ISSUE TITLE
✨ [24.10.20] 작업물 중간 병합 이후 빌드 테스트 진행

### ISSUE THREAD

**Issue by s-ja** [Mt-NextJs/linkle#90]
## Todo

- [ ] `npm run fix`
- [ ] `npm run build`
- [ ] 자동화된 CI/CD 에 따라 vecel에 배포 테스트
  - 에러 발생 시 출력된 로그에 따라 각자 영역에서 수정 및 재 배포 테스트
