### ISSUE TITLE
✨ [24.10.20] 레이아웃 컴포넌트 css 수정

### ISSUE THREAD

**Issue by lumpenop** [Mt-NextJs/linkle#94]
## Todo

- [x] 제목 -> font bold 적용
- [x] 뒤로가기 버튼 inline-block 으로
- [x] 스크롤바 생기는 페이지 영역 조절

**Comment by lumpenop** [comment]
스크롤바를 root 페이지에서 조절해야 하는 것 같아서 보류하였습니다
